// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Eh_1uGLsbKf_a9KrfvDKLVEoe_gKuXo',
    appId: '1:245367500759:web:589c0673bfb0f96383e592',
    messagingSenderId: '245367500759',
    projectId: 'quick-deal-90601',
    authDomain: 'quick-deal-90601.firebaseapp.com',
    storageBucket: 'quick-deal-90601.firebasestorage.app',
    measurementId: 'G-LLVDXPHJVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnGlamY2Qz5UIQ-PmyCOjVdwX-eFzdMJc',
    appId: '1:245367500759:android:7f35a82bd9d1984083e592',
    messagingSenderId: '245367500759',
    projectId: 'quick-deal-90601',
    storageBucket: 'quick-deal-90601.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANvkprMGXsrmS42Biq9dFLcwFjsM5mQ4g',
    appId: '1:245367500759:ios:9f88ff1fe91a1db483e592',
    messagingSenderId: '245367500759',
    projectId: 'quick-deal-90601',
    storageBucket: 'quick-deal-90601.firebasestorage.app',
    iosBundleId: 'com.example.quickdeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANvkprMGXsrmS42Biq9dFLcwFjsM5mQ4g',
    appId: '1:245367500759:ios:9f88ff1fe91a1db483e592',
    messagingSenderId: '245367500759',
    projectId: 'quick-deal-90601',
    storageBucket: 'quick-deal-90601.firebasestorage.app',
    iosBundleId: 'com.example.quickdeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Eh_1uGLsbKf_a9KrfvDKLVEoe_gKuXo',
    appId: '1:245367500759:web:5254d41d58dd5a2083e592',
    messagingSenderId: '245367500759',
    projectId: 'quick-deal-90601',
    authDomain: 'quick-deal-90601.firebaseapp.com',
    storageBucket: 'quick-deal-90601.firebasestorage.app',
    measurementId: 'G-4HSNQ2L889',
  );
}
